### ISSUE TITLE
Content upgrade error

### ISSUE THREAD

**Issue by itzvadi** [PaloAltoNetworks/pandevice#123]
Hello team,

We are using pandevice module to upgrade our firewalls (40 at the same time). Recently we starts getting below errors.  This errors getting from random device. 

Find error below.  Anyone please help on this .

Note: Below segment errors getting from all PAs

Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/tmp/jenkins3175871945205006445.py", line 47, in run
    print_time(self.name, 1, self.counter, self.hostname)
  File "/tmp/jenkins3175871945205006445.py", line 57, in print_time
    device.software.upgrade_to_version("8.0.11-h1")
  File "/usr/local/lib/python2.7/dist-packages/pandevice/updater.py", line 200, in upgrade_to_version
    self.pandevice.content.download_and_install_latest(sync=True)
  File "/usr/local/lib/python2.7/dist-packages/pandevice/updater.py", line 342, in download_and_install_latest
    self.download(sync=sync)
  File "/usr/local/lib/python2.7/dist-packages/pandevice/updater.py", line 309, in download
    "yes" if sync_to_peer else "no")
  File "/usr/local/lib/python2.7/dist-packages/pandevice/updater.py", line 38, in _op
    return self.pandevice.xapi.op(cmd, cmd_xml=True)
  File "/usr/local/lib/python2.7/dist-packages/pandevice/base.py", line 3252, in method
    raise the_exception
PanDeviceXapiError:  request -> content -> upgrade -> download -> latest -> sync-to-peer unexpected here
 request -> content -> upgrade -> download -> latest is invalid

**Comment by btorresgil** [comment]
Fixed in e7f6a3bef3b3c42b24625d80cb9afa11918faf7d.  Thanks for opening the issue!
