### ISSUE TITLE
Unable to apply() or create() SecurityRule with icmp_unreachable attribute defined 

### ISSUE THREAD

**Issue by stealthllama** [PaloAltoNetworks/pandevice#127]
When setting a boolean value for SecurityRule attribute `icmp_unreachable` I get an error when attempting to apply() or create() the object on a live device.

```
>>> foo.about()
{'fromzone': 'outside', 'tozone': 'inside', 'source': ['any'], 'source_user': ['any'], 'hip_profiles': ['any'], 'destination': ['any'], 'application': 'ping', 'service': 'application-default', 'category': ['any'], 'action': 'allow', 'log_setting': None, 'log_start': None, 'log_end': None, 'description': None, 'type': 'universal', 'tag': None, 'negate_source': None, 'negate_destination': None, 'disabled': None, 'schedule': None, 'icmp_unreachable': None, 'disable_server_response_inspection': None, 'group': None, 'negate_target': None, 'target': None, 'virus': None, 'spyware': None, 'vulnerability': None, 'url_filtering': None, 'file_blocking': None, 'wildfire_analysis': None, 'data_filtering': None, 'name': 'Super cool test rule'}
>>> foo.create()
>>> foo.icmp_unreachable = True
>>> foo.create()
Traceback (most recent call last):
  File "/Users/roberthagen/.virtualenvs/ansible-pan/lib/python3.6/site-packages/pandevice/base.py", line 3235, in method
    super_method(self, *args, **kwargs)
  File "/Users/roberthagen/.virtualenvs/ansible-pan/lib/python3.6/site-packages/pan/xapi.py", line 741, in set
    self.__type_config('set', query, extra_qs)
  File "/Users/roberthagen/.virtualenvs/ansible-pan/lib/python3.6/site-packages/pan/xapi.py", line 805, in __type_config
    raise PanXapiError(self.status_detail)
pan.xapi.PanXapiError:  Super cool test rule -> icmp-unreachable is invalid
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/roberthagen/.virtualenvs/ansible-pan/lib/python3.6/site-packages/pandevice/base.py", line 576, in create
    device.active().xapi.set(self.xpath_short(), element, retry_on_peer=self.HA_SYNC)
  File "/Users/roberthagen/.virtualenvs/ansible-pan/lib/python3.6/site-packages/pandevice/base.py", line 3252, in method
    raise the_exception
pandevice.errors.PanDeviceXapiError:  Super cool test rule -> icmp-unreachable is invalid
```
There appears to be a missing `vartype = 'yesno'` in the following parameter definition:
https://github.com/PaloAltoNetworks/pandevice/blob/ea659be1ca89c07931663d529adcbf4e3a4c0196/pandevice/policies.py#L164-L165

**Comment by shinmog** [comment]
Fixed by #128
