### ISSUE TITLE
PanDeviceXapiError when trying to add an Address to an AddressGroup

### ISSUE THREAD

**Issue by vesche** [PaloAltoNetworks/pandevice#141]
I'm trying to add an AddressObject to an AddressGroup, but am getting an XapiError:

```
from pandevice import firewall, objects

pan_ip = "192.168.1.2"
pan_user = "admin"
pan_pass = "password"

fw = firewall.Firewall(pan_ip, pan_user, pan_pass)

block_ip = '11.22.33.44'
ao = objects.AddressObject("Name of block", block_ip, description="Description of block")
fw.add(ao)
ao.create()

address_group_name = 'foo'
objects.AddressGroup.refreshall(fw, add=True)
for ag in fw.children:
    if ag.name == address_group_name:
        our_ag = ag
        break

our_ag.add(ao)
our_ag.apply()
```

Results in:
```
Traceback (most recent call last):
  File "palo_test.py", line 23, in <module>
    our_ag.apply()
  File "/Users/jackson/Library/Python/2.7/lib/python/site-packages/pandevice/base.py", line 554, in apply
    device.active().xapi.edit(self.xpath(), self.element_str(), retry_on_peer=self.HA_SYNC)
  File "/Users/jackson/Library/Python/2.7/lib/python/site-packages/pandevice/base.py", line 3253, in method
    raise the_exception
pandevice.errors.PanDeviceXapiError:  foo -> address unexpected here
```

Not sure why it won't let me apply this.

**Comment by shinmog** [comment]
@vesche 

Address groups don't have address object children.  In fact, address groups don't have children at all.  For static address groups, you want to be updating the `static_value` parameter in address groups to add a new address object.

As a hint, when working with pandevice, if you look at a class' `CHILDTYPES` variable, you'll see what kinds of objects will be underneath that object.  Since `objects.AddressObject` and `objects.AddressGroup` show up under `pandevice.firewall.Firewall`, `pandevice.panorama.Panorama`, and `pandevice.device.Vsys`, you know that you'll only ever find them there.

So in your code, after you get the address group `our_ag`, you'll want to do this instead:

```python
our_ag.static_value.append(ao)
our_ag.apply()
```

Hope this helps!
