### ISSUE TITLE
active-active HA issues in pandevice

### ISSUE THREAD

**Issue by patrickdaj** [PaloAltoNetworks/pandevice#178]
It is not actually possible to apply an ha.HighAvailability object to a firewall due to no device_id in ha.HighAvailability.  Additionally, setup_interface fails on highavailability.HA3 objects due to no "link_duplex" and "link_speed".

from pandevice.firewall import Firewall
from pandevice.ha import *
fw = Firewall(fw_ip, user, passwd)
ha = HighAvailability(enabled=True, group_id=5, peer_ip='192.168.150.2', mode='active-active')
ha1 = HA1(port='ethernet1/5', ip_address='192.168.150.1')
ha2 = HA2(port='ethernet1/6')
ha3 = HA3(port='ethernet1/7')
ha.add(ha1)
ha.add(ha2)
ha.add(ha3)
fw.add(ha)
ha1.setup_interface()
ha2.setup_interface()
ha3.setup_interface()
ha.apply()
Traceback (most recent call last):
  File "<input>", line 14, in <module>
  File "/Users/patrickavery/PycharmProjects/pandevice/pandevice/ha.py", line 125, in setup_interface
    if self.link_speed is not None:
AttributeError: 'HA3' object has no attribute 'link_speed'

! ethernet1/7 was configured from GUI as HA to get past last error.

ha.apply()
Traceback (most recent call last):
  File "/Users/patrickavery/PycharmProjects/pandevice/pandevice/base.py", line 3469, in method
    super_method(self, *args, **kwargs)
  File "/Users/patrickavery/PycharmProjects/pandevice/venv/lib/python3.6/site-packages/pan_python-0.15.0-py3.6.egg/pan/xapi.py", line 749, in edit
    self.__type_config('edit', query, extra_qs)
  File "/Users/patrickavery/PycharmProjects/pandevice/venv/lib/python3.6/site-packages/pan_python-0.15.0-py3.6.egg/pan/xapi.py", line 805, in __type_config
    raise PanXapiError(self.status_detail)
pan.xapi.PanXapiError:  high-availability -> group -> mode -> active-active  is missing 'device-id'
 high-availability -> group -> mode -> active-active is invalid
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/patrickavery/PycharmProjects/pandevice/pandevice/base.py", line 561, in apply
    device.xapi.edit(self.xpath(), self.element_str(), retry_on_peer=self.HA_SYNC)
  File "/Users/patrickavery/PycharmProjects/pandevice/pandevice/base.py", line 3486, in method
    raise the_exception
pandevice.errors.PanDeviceXapiError:  high-availability -> group -> mode -> active-active  is missing 'device-id'
 high-availability -> group -> mode -> active-active is invalid

**Comment by patrickdaj** [comment]
Submitted PR180 to fix these issues along with some enhancements for active-active.

https://github.com/PaloAltoNetworks/pandevice/pull/180

**Comment by shinmog** [comment]
Fixed by #180, thanks @patrickdaj
