### ISSUE TITLE
PanOS upgrade from 8.0.13 to 8.1.15 fail (SoftwareUpdater(device).upgrade_to_version(version, False))

### ISSUE THREAD

**Issue by DDmchk** [PaloAltoNetworks/pandevice#243]
Hello, team
## Describe the bug

Using "SoftwareUpdater(device).upgrade_to_version(version, False)" to upgrade PanOS from different levels to 8.1.15.
for versions 8.1.x it works, but when trying to upgrade 8.0.x (or earlier) it fails

## Expected behavior

expecting function to do consequent upgrades to desired version with installation of base images

## Current behavior

Traceback (most recent call last):
  File "panos_upgrade.py", line 50, in <module>
    SoftwareUpdater(device).upgrade_to_version(version, False)
  File "/usr/local/lib/python3.6/site-packages/pandevice/updater.py", line 207, in upgrade_to_version
    self.download_install_reboot(next_version, sync=True)
  File "/usr/local/lib/python3.6/site-packages/pandevice/updater.py", line 126, in download_install_reboot
    self.download_install(version, load_config, sync=True)
  File "/usr/local/lib/python3.6/site-packages/pandevice/updater.py", line 118, in download_install
    self.download(target_version, sync=True)
  File "/usr/local/lib/python3.6/site-packages/pandevice/updater.py", line 64, in download
    (self.pandevice.id, version, result['messages']))
pandevice.errors.PanDeviceError: Device xxxxxxx attempt to download version 8.1.15-h3 failed: ['Successfully 'Preloading into software manager', "The required '8.1.0' base image must be loaded before this image can be loadet have to install or run the base image, only download it.  Once the base is loaded, re-download your target image to load into software manager. Please retry.', 'Post processing failed. Please retry.']

## Steps to reproduce

upgrade from v.8.0.13 to 8.1.15-h3

## Your Environment

using hardware model PA-220

**Comment by btorresgil** [comment]
Thanks for the bug report. We fixed an issue recently in the upgrader, but the fix hasn't been released yet.

https://github.com/PaloAltoNetworks/pandevice/pull/216

I recommend to try using the 'develop' branch and check if it fixes your issue. We're trying to release this fix ASAP, but we're also changing our release process, so it's taking a while. Sorry for the delay.
